name: OllieJT
favicon: null
layout_spectrum: 0.87646
typography_spectrum: 0.63272
title: My test website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d4e7d4'
    - '#b1c9af'
    - '#2e3813'
    - '#7b8263'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
