name: OllieJT
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47662
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#31678c'
    - '#ee383a'
    - '#2e4859'
    - '#000000'
    - '#005555'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
