name: OllieJT
favicon: null
layout_spectrum: 0.3660462952684611
typography_spectrum: 0.7391063324175775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#31678c'
    - '#ee383a'
    - '#ff0000'
    - '#000000'
    - '#000080'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
